name: test

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # - target: x86_64-apple-darwin
          #   os: macos-13
          # - target: aarch64-apple-darwin
          #   os: macos-latest
          # - target: x86_64-pc-windows-gnu
          #   os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-A warnings"
          toolchain: "nightly"
      - name: build-${{ matrix.target }}
        run: |
          cargo --version
          rustc -Vv
          echo "print(1+1)" >> test.js

          cargo run test.js
          cargo install --path .

      - name: install mujs
        uses: ahaoboy/easy-setup@v1
        with:
          url: |-
            https://github.com/ahaoboy/mujs-build
            https://github.com/pnpm/pnpm

      - name: bench
        run: |
          git clone https://github.com/ahaoboy/js-engine-benchmark
          cd js-engine-benchmark
          npm run build

          node dist/run.js
          mujs-one dist/run.js
          mujs dist/run.js

      - name: react
        run: |
          git clone https://github.com/ahaoboy/mujs-react
          cd mujs-react
          pnpm install
          pnpm run build

          mujs-one es5/index.js
          mujs-one es5/bench.js
          mujs es5/index.js
          mujs es5/bench.js
